create_event:
    pattern: /createevent
    defaults: {_controller: CETestBundle:Default:createEvent }


ce_test_event_editor:
    pattern: /eventEdit
    defaults: {_controller: CETestBundle:Default:eventEdit }


ce_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CETestBundle:Default:index }

ce_test_event:
    pattern:  /event
    defaults: { _controller: CETestBundle:Event:getDateEvent }

ce_test_calendar:
    pattern:  /calendars
    defaults: { _controller: CETestBundle:Event:getCalendars }

show_calendar:
    pattern:  /calendar
    defaults: { _controller: CETestBundle:Default:showCalendar }

get_dates:
    pattern: /getdates
    defaults: { _controller: CETestBundle:Default:getDates }