ce_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CETestBundle:Default:index }

ce_time_tracker:
    pattern:  /tracker
    defaults: { _controller: CETestBundle:TimeTracker:index }